### PR TITLE
Implementation of Print Scaling for Img and Slide Show Cells

### PR DESCRIPTION
**Pull request by LennartF22**
While using wxMaxima, I noticed that images usually appear way too small (depending on the dpi of the printer), and that the print scale in the configuration menu does not affect the size of images (like graphs) at all.

Therefore I quickly fixed this issue by myself (maybe in a crude way, because this is the first time working at the wxMaxima source for me, but idk).

While the size of the images is equal between different printer dpi settings now, I think that the font of normal math cells is way too large at 600 dpi, but this has nothing to do with my branch and is a problem with the current master branch.

### CODE REVIEW

**Comment by gunterkoenigsmann** [comment]
For the printing scale we'll need any help that we can get. And for the right mapping between the image scale on the screen and on paper I don't have any preference:

- I don't use printing
- On the screen the images if they fit on the screen are currently shown in their original size - and if they don't they are scaled down. On a 640x480 pixel monitor this means that an 800x600 image is scaled down, on an Ultra HD screen it is more or less of thumbnail size. Don't know which of the two we should use on the printer. 
I don't know if "1" is the correct scale for printing, though: This would mean that images are on a different size if printed at 1200dpi instead of 300dpi. Also the rabbit hole goes deeper as issue #947 shows: I still have no idea how to find out to which value the global scale has to be set in order to make the fonts appear at the right size. ...and if this scale is set up correctly this is likely to change the size of the printed images again.

Do you develop on windows? On linux I have no idea how to get the correct global scaling factor for printing, too (the scaling factor of the print seems somehow to depend on the zoom factor on the screen but I cannot find any reason why). But on MSW I don't even have a system I can test on.

For the toolbar icons I am still playing with the thought of having two sets of icons: One of 128x128 pixel size and one of 192x192: Scaling icons down by a factor that isn't 2^n if the screen resolution requires that blurs them. But limiting scaling to factors of 2^n means that the choice of scaling factos is a little bit too coarse. But how do I make this work together with styling and icon sets on wxgtk?

Kind regards,
  Gunter.

**Comment by LennartF22** [comment]
As I'm using wxMaxima for school very often, I'm reliant on proper printing, so I'll also have a look at the font scaling later on.

I'm mainly developing on linux. Yesterday I tried to build wxWidgets on Windows with MinGW, but after ~2h I gave up, because there was one error after another. I'll try to build it with Visual Studio today.

Using multiple sets of icons sounds like a good idea to me, as this would cause that the factor to the next lower scale would be alternating between 3/4 and 2/3. If this isn't enough, you could use four sets (e. g. 128x128, 160x160, 192x129 and 224), which would result in a "downscaling" factor of at least 0.8 (definetly high enough for the toolbar icons), but maybe four sets are just overkill.

If you want to, I could experiment with this approach.

Best Regards,
Lennart

**Comment by gunterkoenigsmann** [comment]
Thanks a lot! With the print scaling I am somehow lost.

If you send me the toolbar improvements in a separate pull request I'll commit them to master. Normally I call 

     optipng -o 9

on any .png images before committing them. But that's optional as inkscape already produces quite small .png images.

---

About wxSvg: That would enable adding nice vector graphics to the worksheet, as well as using the svg output of gnuplot. But I don't know if there is a good way of exporting svg to word and the extra dependency means much work (eventually including getting wxSvg into debian and ubuntu again) and also more effort to be needed for creating binaries...

**Comment by LennartF22** [comment]
I was able to find and fix the reason why font look larger/smaller at different dots/pixels per inch (the zoom factor was applied two times for fonts, first in the GetFontSize() method, and then by the Scale_Px() method).

I normalized the dpi to 72 dpi, which means that the height of a 12pt font equals about 12/72 inches (I think this is the same method many office programs use). I also made the printout zoom factor independent of the "normal" zoom factor, as I think that a printout of the same document should look the same every time, independent of the machine and how far the user zooms in. That's why the print scale factor in the configuration exists, anyhow.

The images are normalized to 96 ppi, which means that one inch of the printout contains 96 pixels, independent of the dpi of the printer.

Things aren't really optimal yet, but everything looks kind of okay now:

- [300 dpi, linux, my branch](https://github.com/andrejv/wxmaxima/files/1649300/output_300_new.pdf)
- [600 dpi, windows, my branch](https://github.com/andrejv/wxmaxima/files/1649302/output_600_new.pdf)
- [300 dpi, linux, master](https://github.com/andrejv/wxmaxima/files/1649301/output_300_old.pdf)
- [600 dpi, windows, master](https://github.com/andrejv/wxmaxima/files/1649303/output_600_old.pdf)

Some margins don't seem to scale correctly, but this seems to be a minor problem. A major problem is that the lines aren't broken correctly (as you can see in the 600 dpi printout), probably caused by wrong scaling.

I also fixed a bug which existed for a long time and affects cells with multiple outputs, as you can see in the document below:

[output.pdf](https://github.com/andrejv/wxmaxima/files/1649299/output.pdf)

Actually, I think the best thing to do would be to rewrite the whole rendering code to do everything properly from the beginning, because it will be hard to fix everything. Some parts look very messy and it looks like many things are just afterthoughts, which had to be implemented somehow, but that's just my opinion. I don't think that I have the time to rewrite the graphical stuff after all, even though I'm really motivated to to that...

I committed everything that has to do with printing to this branch (therefore I created a different branch for the toolbar icons), but if you want to, I can create separate branches for different bug fixes or improvements.

**Comment by gunterkoenigsmann** [comment]
The code is messy for the following reasons:

- On the mac platform all wxMaxima windows share the same process, but need separate Configuration and MathCell::CellPointers objects
- On some operating systems wxArtProvider provides bitmaps that match the rest of the visual style (and therefore should supersede the bitmaps wxMaxima comes with
- Some of these bitmaps are of a completely wrong size in some styles.
- The antialiasing DC on Windows has problems with (was it OpenType fonts?)

If you find other things that are messy - I would be happy for any improvement.

---

I think by merging the other branch I have broken something here. Could you do a 

     git rebase master

...if you promise me that

- on MSW resolutions !=600dpi work
- a bitmap that was created after a wxplot_size:[10000,10000]; is scaled down on print to fit on paper
- and a bitmap that by the right-click menu (this one exists only for images that were inserted using "insert/image cells" from the menu (as I don't know how to handle cells with limited size being deleted and re-added on recalculation of the worksheet)) has been limited to a size is limited to a size

...this branch urgently needs merging as it fixes most of the known bugs.

**Comment by gunterkoenigsmann** [comment]
Ok... ...I have managed to resolve the conflict. Hope I did it right.

**Comment by LennartF22** [comment]
Alright,
on MSW resolutions != 600 dpi work as well (I just used 600 for MSW and 300 for Linux, as the pdf printer of Windows 10 comes with 600 dpi and the pdf printer on Ubuntu comes with 300 dpi).

Big bitmaps are also printed properly, because I use the same method that was used for scaling before, just with a different initial scale for printing.

Inserted images are printed properly as well, even though wxMaxima crashes when trying to delete the inserted picture, but I doubt that this has something to do with the print scaling. Maybe it's just an issue with my build, but I don't know.
image

Kind regards,
Lennart

**Comment by gunterkoenigsmann** [comment]
Can you get a stack trace? Normally MS Visual Studio allows you to see which function has called the function List has crashed in in which line. And which function has called this function and...

...the last months I have spent much time working on historically grown things like:

- there were 3 mechanisms that determined which cell inside a cell inside a cell objects were in
- Many mechaniss need pointers to cells (the one that is currently active, the queue of cells needing processing, the start and the end of the selection, the last cell maxima output something into, the last cell that gave an error,...) => tried to automative invalidating these pointers if a cell was deleted.
- there were two functions that created wxm code and two functions that interpreted the code
- There were 3 mechanisms that determined how high and how wide a cell is.

I expect that trying to simplify the code it was me who has broken this.

**Comment by LennartF22** [comment]
Just noticed that this happens when deleting any cell, hope this can help:

```
 	msvcp140d.dll!00007ffc352cf846()	Unbekannt	Nichtbenutzercode. PDB-Datei wurde nicht gefunden oder konnte nicht geöffnet werden.
 	wxmaxima.exe!std::_List_const_iterator<std::_List_val<std::_List_simple_types<GroupCell * __ptr64> > >::operator*() Zeile 187	C++	Nichtbenutzercode. Symbole wurden geladen.
 	wxmaxima.exe!std::_List_iterator<std::_List_val<std::_List_simple_types<GroupCell * __ptr64> > >::operator*() Zeile 332	C++	Nichtbenutzercode. Symbole wurden geladen.
 	wxmaxima.exe!std::list<GroupCell * __ptr64,std::allocator<GroupCell * __ptr64> >::front() Zeile 1192	C++	Nichtbenutzercode. Symbole wurden geladen.
>	wxmaxima.exe!EvaluationQueue::Remove(GroupCell * gr) Zeile 62	C++	Symbole wurden geladen.
 	wxmaxima.exe!MathCtrl::DeleteRegion(GroupCell * start, GroupCell * end, std::list<MathCtrl::TreeUndoAction *,std::allocator<MathCtrl::TreeUndoAction *> > * undoBuffer) Zeile 2480	C++	Symbole wurden geladen.
 	wxmaxima.exe!MathCtrl::DeleteRegion(GroupCell * start, GroupCell * end) Zeile 2453	C++	Symbole wurden geladen.
 	wxmaxima.exe!MathCtrl::DeleteSelection() Zeile 2291	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxMaxima::EditMenu(wxCommandEvent & event) Zeile 4132	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxAppConsoleBase::HandleEvent(wxEvtHandler * handler, void(wxEvtHandler::*)(wxEvent &) func, wxEvent & event) Zeile 658	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxAppConsoleBase::CallEventHandler(wxEvtHandler * handler, wxEventFunctor & functor, wxEvent & event) Zeile 670	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEvtHandler::ProcessEventIfMatchesId(const wxEventTableEntryBase & entry, wxEvtHandler * handler, wxEvent & event) Zeile 1383	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEventHashTable::HandleEvent(wxEvent & event, wxEvtHandler * self) Zeile 989	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEvtHandler::TryHereOnly(wxEvent & event) Zeile 1578	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEvtHandler::TryBeforeAndHere(wxEvent & event) Zeile 3656	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEvtHandler::ProcessEvent(wxEvent & event) Zeile 1480	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEvtHandler::DoTryChain(wxEvent & event) Zeile 1543	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEvtHandler::ProcessEventLocally(wxEvent & event) Zeile 1511	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEvtHandler::ProcessEvent(wxEvent & event) Zeile 1484	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxWindowBase::ProcessWindowEvent(wxEvent & event) Zeile 861	C++	Symbole wurden geladen.
 	wxmaxima.exe!MathCtrl::OnKeyDown(wxKeyEvent & event) Zeile 2803	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxAppConsoleBase::HandleEvent(wxEvtHandler * handler, void(wxEvtHandler::*)(wxEvent &) func, wxEvent & event) Zeile 658	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxAppConsoleBase::CallEventHandler(wxEvtHandler * handler, wxEventFunctor & functor, wxEvent & event) Zeile 670	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEvtHandler::ProcessEventIfMatchesId(const wxEventTableEntryBase & entry, wxEvtHandler * handler, wxEvent & event) Zeile 1383	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEventHashTable::HandleEvent(wxEvent & event, wxEvtHandler * self) Zeile 989	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEvtHandler::TryHereOnly(wxEvent & event) Zeile 1578	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEvtHandler::TryBeforeAndHere(wxEvent & event) Zeile 3656	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEvtHandler::ProcessEventLocally(wxEvent & event) Zeile 1511	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEvtHandler::ProcessEvent(wxEvent & event) Zeile 1484	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxScrollHelperEvtHandler::ProcessEvent(wxEvent & event) Zeile 200	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEvtHandler::SafelyProcessEvent(wxEvent & event) Zeile 1602	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxWindowBase::HandleWindowEvent(wxEvent & event) Zeile 1535	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxWindow::HandleKeyDown(unsigned __int64 wParam, __int64 lParam) Zeile 5645	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxWindow::MSWHandleMessage(__int64 * result, unsigned int message, unsigned __int64 wParam, __int64 lParam) Zeile 2968	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxWindow::MSWWindowProc(unsigned int message, unsigned __int64 wParam, __int64 lParam) Zeile 3524	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxScrolled<wxWindow>::MSWWindowProc(unsigned int nMsg, unsigned __int64 wParam, __int64 lParam) Zeile 436	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxWndProc(HWND__ * hWnd, unsigned int message, unsigned __int64 wParam, __int64 lParam) Zeile 2667	C++	Symbole wurden geladen.
 	[Externer Code]		Frame mit Anmerkungen
 	wxmaxima.exe!wxGUIEventLoop::ProcessMessage(tagMSG * msg) Zeile 169	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxGUIEventLoop::Dispatch() Zeile 229	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEventLoopManual::ProcessEvents() Zeile 228	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEventLoopManual::DoRun() Zeile 273	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEventLoopBase::Run() Zeile 76	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxAppConsoleBase::MainLoop() Zeile 380	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxAppConsoleBase::OnRun() Zeile 302	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxAppBase::OnRun() Zeile 312	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEntryReal(int & argc, wchar_t * * argv) Zeile 503	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEntry(int & argc, wchar_t * * argv) Zeile 181	C++	Symbole wurden geladen.
 	wxmaxima.exe!wxEntry(HINSTANCE__ * hInstance, HINSTANCE__ * __formal, char * __formal, int nCmdShow) Zeile 290	C++	Symbole wurden geladen.
 	wxmaxima.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * __formal, int nCmdShow) Zeile 52	C++	Symbole wurden geladen.
 	[Externer Code]		Frame mit Anmerkungen

```

**Comment by gunterkoenigsmann** [comment]
I am still unsure what that means: EvaluationQueue::Remove cannot possibly segfault in this line.
---
For the automatic line breaks on (*m_configuration)->SetClientWidth() is called by MathPrintOut. After that a Recalculation of the EditorCell should recalculate all line break => Either the SetClientWidth() gets the wrong argument or the Recalculation is no more called.
---
There seems to be a factor that affects scaling on MSW and that we still don't consider, see the attached file.
[test.pdf](https://github.com/andrejv/wxmaxima/files/1651738/test.pdf)

**Comment by LennartF22** [comment]
> I am still unsure what that means: EvaluationQueue::Remove cannot possibly segfault in this line.
Are you referring to the stack trace? I was already able to fix this problem. It was caused by calling list::front() on empty lists.

> There seems to be a factor that affects scaling on MSW and that we still don't consider, see the attached file.
Strange, might be a dumb question, but you have set the zoom factor to 1.0, right?

**Comment by gunterkoenigsmann** [comment]
I have. Herbert and richardgobeli always had different print scales even before I had introduced this setting so they could at least manually choose the correct printing scale => something strange is going on there...
...but on my linux computer printing seems to have improved a lot.

**Comment by gunterkoenigsmann** [comment]
If you want to send me a mail: every mail that arrives at physikbuch.de (no matter what comes before the "at" sign) will reach me.

**Pull request merged**
